# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-4.0.8
    secrets: inherit
    with:
      tests-env-files: .ci_support/environment.yml .ci_support/environment-tests.yml
      do-benchmark-tests: false
      python-version-alt1: '3.11'
      python-version-alt2: '3.12'
      python-version: '3.13'
      python-version-alt3: '3.14'
      do-codecov: true
      do-codacy: false
      do-coveralls: false
      do-ruff-check: true
      do-mypy: true
