# This runs jobs which pyiron modules should run on release
# This job runs on pull requests and does not actually publish anything to pypi
# It is useful for debugging new build recipes
# To actually release, change the `on` and `publish-to-pypi` fields
name: Release

on:
  pull_request:
  release:
    types: [ published ]

jobs:
  hatchling-release:
    uses: pyiron/actions/.github/workflows/hatch-release.yml@actions-4.0.8
    secrets: inherit
    with:
      publish-to-pypi: ${{ github.event_name == 'release' && github.event.action == 'published' }}