# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Try code-cov

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pyiron/actions/unit-tests@use_miniconda
        with:
          python-version: '3.12'
          env-files: .ci_support/environment.yml .ci_support/environment-tests.yml
      - name: Coverage
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage combine
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: pyiron/pyiron_snippets